namespace BenchmarkGraph;

public class LazyProduct
{
    public int Id { get; }

    public async Task<string> GetField01Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field01;
    public async Task<int> GetField02Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field02;
    public async Task<bool> GetField03Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field03;
    public async Task<string> GetField04Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field04;
    public async Task<int> GetField05Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field05;
    public async Task<bool> GetField06Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field06;
    public async Task<string> GetField07Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field07;
    public async Task<int> GetField08Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field08;
    public async Task<bool> GetField09Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field09;
    public async Task<string> GetField10Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field10;
    public async Task<int> GetField11Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field11;
    public async Task<bool> GetField12Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field12;
    public async Task<string> GetField13Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field13;
    public async Task<int> GetField14Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field14;
    public async Task<bool> GetField15Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field15;
    public async Task<string> GetField16Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field16;
    public async Task<int> GetField17Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field17;
    public async Task<bool> GetField18Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field18;
    public async Task<string> GetField19Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field19;
    public async Task<int> GetField20Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field20;
    public async Task<bool> GetField21Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field21;
    public async Task<string> GetField22Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field22;
    public async Task<int> GetField23Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field23;
    public async Task<bool> GetField24Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field24;
    public async Task<string> GetField25Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field25;
    public async Task<int> GetField26Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field26;
    public async Task<bool> GetField27Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field27;
    public async Task<string> GetField28Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field28;
    public async Task<int> GetField29Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field29;
    public async Task<bool> GetField30Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field30;
    public async Task<string> GetField31Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field31;
    public async Task<int> GetField32Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field32;
    public async Task<bool> GetField33Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field33;
    public async Task<string> GetField34Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field34;
    public async Task<int> GetField35Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field35;
    public async Task<bool> GetField36Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field36;
    public async Task<string> GetField37Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field37;
    public async Task<int> GetField38Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field38;
    public async Task<bool> GetField39Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field39;
    public async Task<string> GetField40Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field40;
    public async Task<int> GetField41Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field41;
    public async Task<bool> GetField42Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field42;
    public async Task<string> GetField43Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field43;
    public async Task<int> GetField44Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field44;
    public async Task<bool> GetField45Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field45;
    public async Task<string> GetField46Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field46;
    public async Task<int> GetField47Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field47;
    public async Task<bool> GetField48Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field48;
    public async Task<string> GetField49Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field49;
    public async Task<int> GetField50Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field50;
    public async Task<bool> GetField51Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field51;
    public async Task<string> GetField52Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field52;
    public async Task<int> GetField53Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field53;
    public async Task<bool> GetField54Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field54;
    public async Task<string> GetField55Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field55;
    public async Task<int> GetField56Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field56;
    public async Task<bool> GetField57Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field57;
    public async Task<string> GetField58Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field58;
    public async Task<int> GetField59Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field59;
    public async Task<bool> GetField60Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field60;
    public async Task<string> GetField61Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field61;
    public async Task<int> GetField62Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field62;
    public async Task<bool> GetField63Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field63;
    public async Task<string> GetField64Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field64;
    public async Task<int> GetField65Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field65;
    public async Task<bool> GetField66Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field66;
    public async Task<string> GetField67Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field67;
    public async Task<int> GetField68Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field68;
    public async Task<bool> GetField69Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field69;
    public async Task<string> GetField70Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field70;
    public async Task<int> GetField71Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field71;
    public async Task<bool> GetField72Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field72;
    public async Task<string> GetField73Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field73;
    public async Task<int> GetField74Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field74;
    public async Task<bool> GetField75Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field75;
    public async Task<string> GetField76Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field76;
    public async Task<int> GetField77Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field77;
    public async Task<bool> GetField78Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field78;
    public async Task<string> GetField79Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field79;
    public async Task<int> GetField80Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field80;
    public async Task<bool> GetField81Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field81;
    public async Task<string> GetField82Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field82;
    public async Task<int> GetField83Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field83;
    public async Task<bool> GetField84Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field84;
    public async Task<string> GetField85Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field85;
    public async Task<int> GetField86Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field86;
    public async Task<bool> GetField87Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field87;
    public async Task<string> GetField88Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field88;
    public async Task<int> GetField89Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field89;
    public async Task<bool> GetField90Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field90;
    public async Task<string> GetField91Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field91;
    public async Task<int> GetField92Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field92;
    public async Task<bool> GetField93Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field93;
    public async Task<string> GetField94Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field94;
    public async Task<int> GetField95Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field95;
    public async Task<bool> GetField96Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field96;
    public async Task<string> GetField97Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field97;
    public async Task<int> GetField98Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field98;
    public async Task<bool> GetField99Async(DataProductDataLoader dataLoader) => (await dataLoader.LoadAsync(Id)).Field99;

    public LazyProduct(int id)
    {
        Id = id;
    }
}